### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by Nivl** [squarewolf/node-neuter#5]
tl;dr: You need to create the version 0.1.3 from master, and update the npm repo.

I'm using gulp-neuter, and it crashes when I'm building my JS files.

```
if (childNode.type === 'FunctionDeclaration' ||
	         ^
TypeError: Cannot read property 'type' of null
```

I looked around and I realized that the bug was coming from the current version of node-neuter (0.1.2). By replacing the node-neuter files (included by gulp-neuter) by the one from the master branch, the bug goes away. So in order to make everything working, you need to create a version 0.1.3 from master, and to update the npm repo.

**Comment by tvervest** [comment]
Done! :+1:
